# #docker compose is used to run docker image easily from our location and can manage multiple service
#
# version: "3"  # docker version
#
# services:
#   web:
#     build:
#       context: .
#     ports:
#       - "8000:8000"
#     volumes:   #docker file if there is change into the local code it can be updated on the docker file
#       - ./app:/app
#     command: >  #breaking command use the > symbol #to run application in the dcker container   #0.0.0.0 all the ip which is running in doker server
#       pyhton manage.py runserver 0.0.0.0:8000
#
#
#
#   #docker-compose build to run
#   #docker-compose run app app sh -c "django-admin.py startproject app ."
#   #sh=shell,-c=command , app=name of the service


version: '3'

services:
 app:
   build:
     context: D:\Jose\python_course\DjangoApp
   ports:
     - "8000:8000"
   volumes:
     - .\app:/app
   command: >
      python manage.py runserver 0.0.0.0:8000
